# See config.example.yml for documentation.
object_base: orig/WPSE01
object: main.dol
symbols: config/WPSE01/symbols.txt
splits: config/WPSE01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
# mw_comment_version: 11

# modules:
# - object: files/module.rel
#   symbols: config/WPSE01/module/symbols.txt
#   splits: config/WPSE01/module/splits.txt
